### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by thekevinbrown** [rsms/js-miniglob#1]
On version 0.1.2, when I run `yarn test`, I get the following:

```console
$ node test/test.js
test match
assert.js:394
    throw err;
    ^

AssertionError [ERR_ASSERTION]: match("a*", "ab/c") => MATCH; expected NOMATCH
    at Object.<anonymous> (D:\Users\kevin\development\js-miniglob\test\test.js:92:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is this expected on Windows? We're trying to use Estrella in that environment (https://github.com/rsms/estrella/issues/48), which depends on this package.

**Comment by pjeby** [comment]
The tests are failing because this package doesn't really work on Windows: it's not treating `/` and `\` as the same character for matching purposes, and so can't generate any sort of consistent results.

Apparently this is actually a failing of the upstream library from which this is ported: Go disables backslash-escaping on Windows and doesn't do portable glob paths.

Basically, nobody should use this library if they want to use platform-independent glob patterns; the node-glob library would probably be a better choice.
